#### COLLECTION ####
valentino_collection_name = " VALENTINO HAUTE COUTURE SS23"

## DEFINE THE TRENDS
valentino_trends = {
  #material and texture
  'sheer': 0,
  'plaid':0, 
  'ruffles':0,
  'stockings':0,
  'stripes':0, 
  'leather':0,
  'fur':0,

  #items 
  'blazer':0, 
  'v_neck':0, 
  'hat':0,
  'costume_jewelry':0, 
  'strapless':0, 
  'asymmetric':0,
  'mini_dress':0,
  'button_down':0, 
  'shorts':0,
  'hot_shorts':0, 
  'maxi_dress':0,
  'maxi_skirt':0,
  'jeans':0,
  'crossbody_bag':0, 
  'clutch':0, 
  'gloves':0,
  'tie':0,
  'bow':0,
  'maxi':0,
  'parachute pants':0,
  'cape':0,
  'goggles':0,
  'button_up':0,
  'fishnet':0,
  'long_coat':0,

  'valentino_logo':0, 

  #colors
  'red':0, 
  'purple':0,
  'black':0, 
  'blue':0, 
  'yellow':0, 
  'pink':0, 
  'orange':0, 
  'white':0, 
  'navy':0, 
  'green':0, 
  'shimmer':0, 
  'grey':0,

  #shoes
  'ankle_straps':0, 
  'open_toe':0, 
  'ballet_flats':0,
  'platform_heels':0,
  'boots':0,
  'close_toed':0,
  }      

## DEFINE THE LOOKS
valentino_looks = [
['tie','pink','white','black','blazer','button_up','bow', 'ballet_flats' ], #look1
['black','close_toed','goggles','blazer'],
['black','polka_dots','stockings' ,'ankle_strap'],
['pink','black','white','googles','cape','fishnet','polka_dots','stockings','platform_heels'],
['black','pink','parachute_pant','long_coat'],
['pink','silk','maxi'],
['long_coat','brown','white','pink', 'bow', 'fur','ballet_flats'],
['brown','ruffle','ballet_flats'],
['brown','shimmer','gloves','ballet_flats'],
['shimmer','blue','black','button_up','long_coat','boots'],
['orange','purple','bow','gloves','platform_heels'],
['ruffle','long_coat','plaform_heels' ,'leggings','orange'],
['pink','brown','parachute_pants'],
['ruffle','shimmer','red','pink','ballet_flats'],
['leggings','green','shimmer','pink','ruffle','gloves','ballet_flats'],
['ruffle','pink','black','brown','gloves','ballet_flats'],
['long_coat','leggings','platform_heels','ruffle','brown','green','pink'],
['long_coat', 'ruffle','polka_dots' 'stockings','green','ballet_flats','black','white'], #look18
['ruffle','cape', 'stripes','ballet_flats','pink','black','green'],
['pink', 'long_coat','white','black',],
['pink','maxi','bow', 'close_toed'],
['pink','black', 'gloves', 'maxi', 'polka_dots','ruffle','close_toed'],
['ruffle','gloves','ballet_flats' ,'pink','black','green'],
['stripes','pink','bow','black','yellow', 'ballet_flats'],
['cape','pink','shimmer','fur', 'bow', 'ballet_flats'],
['black', 'gloves', 'ballet_flats'],
['cape','black','ankle_strap'] , #look27
['tie','boots','button_up','black','white'],
['fishnet','ruffle','black'],
['black','feather','ankle_strap','pink'],
['black','maxi','bow','white'],
['long coat','fur','button_up','blue'],
['blazer','tie','button_up','shimmer','black','white'],
['striped','blazer,'bow','pink', 'ballet_skirt','black','white'],
['blazer','ruffle','shimmer','fishnet','stockings','gloves','black','white'],
['black','gloves'],
['white','net','ballet_flats'],
['white','maxi','black','bow'],
['polka_dots', 'white','maxi','close_toed','ankle_strap','brown'],
['blazer','boots','tie','button_up','yellow','black','white'],
['tie','button_up','yellow', 'white','black','polka_dots'],
['polka dots','long_coat,'bow','tie','button_up','ballet_flats','black,'blue','off_white'],
['bow','green', 'maxi','platform_heels'],
['ruffle','maxi','platform_heels','green','black'], #look44
['purple','sheer','maxi_dress', 'bow'], # LOOK 45
['purple', 'black', 'stockings', 'gloves', 'leather', 'purple' 'ballet_flats','bow'],
['platform_heels', 'purple', 'maxi_dress', 'asymmetric'],
['blazer', 'tie', 'button_down', 'purple', 'boots', 'leather'],
['purple', 'ruffles','maxi_dress', 'white', 'bow'],
['yellow', 'purple', 'black','bow', 'blazer'],
['ruffles', 'yellow', 'pink','ankle_straps'],
['bow', 'gloves','purple', 'pink', 'red', 'maxi_dress'],
['ruffles', 'purple', 'red', 'stiletto', 'gloves', 'leather'],
['red', 'pink', 'leahter', 'blazer'],
['red', 'leather', 'gloves'], #LOOK  55
['blazer', 'red', 'shimmer'],
['red','floral', 'stiletto'],
['tie', 'red', 'leather', 'feathers'],
['red', 'platform_heels','sheer'],
['bow', 'red', 'maxi_dress'],
['ruffles','sheer', 'shimmer','silver'],
['pink','silver','shimmer'],
['gold','ruffles','shimmer'],
['pink','blazer', 'leather'],
['leather', 'gloves','shimmer','green'],
['blazer','green','leather'],
['blue','maxi_dress','platform_heels'],
['silver','bow','shimmer','sheer'],
['pink','stocking','shimmer','bow'],
['ruffles','silver','platform_heels'],
['stocking','shimmer','gloves','leather'],
['yellow','silver','ruffles'],
['golden', 'pink','maxi_dress','shimmer'],
['pink','shimmer','leather'],
['mini_skirt', 'shimmer','stocking','leather','sheer'],
['leather','platform_shoes','sheer'],
['bow'],
['blazer','leather','sheer'],
['ruffles','stocking','sheer','mini_skirt'],
['pink','feather','polka_dots','stocking'],
['bow','pink','gloves','platform_heels'],
['tie','leather','shimmer'],
['pink','mini_skirt','shimmer','platform_heels'],
['pink','leather','gloves'],
['ruffles','shimmer','pink','leather'],
['shimmer','ruffles'],
['ruffles'],
['ruffles'],
['ruffles','feather','polka_dots','shimmer','bow']
]
